# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 060176388132d0a552ea41952dc1e07fc80c2f368feebc6207ebf4d6d145ced10e86d5d3ab43aec39f9dcb8b6e3c290f664e004b0cfcaecb4fff7e26ab30b7f2

test:
  secret_key_base: 68256477ec30f912a591ac2fac5efd785702785c18eb51f3a8a030d0619700577219e98623527744a5415517074d6306de79563332693a10482e498e734fa97b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
